/*DROP TABLE IF EXISTS url CASCADE;
DROP TABLE IF EXISTS ip CASCADE;
DROP TABLE IF EXISTS port CASCADE;*/

CREATE TABLE IF NOT EXISTS url (
    id SERIAL PRIMARY KEY,
    value TEXT NOT NULL UNIQUE ,
    active BOOLEAN NOT NULL DEFAULT false,
    mode TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ip (
    id SERIAL PRIMARY KEY,
    value TEXT NOT NULL UNIQUE ,
    mode TEXT NOT NULL,
    active BOOLEAN default false
);

CREATE TABLE IF NOT EXISTS port (
    id SERIAL PRIMARY KEY,
    value INTEGER NOT NULL UNIQUE ,
    mode TEXT NOT NULL,
    active BOOLEAN default false
);


